### PR TITLE
feat(macOS) Add macOS support

### PR DESCRIPTION
**Pull request by ajpinedam**
This PR adds macOS support to the library.

In order to do this, we had to upgrade the Uno.UI dependencies to the latest as well as other dependencies (ex: Android Version).

### CODE REVIEW

**Comment by ajpinedam** [comment]
...

**Comment by ajpinedam** [comment]
@jeromelaban  ready to be merged. It'd be good to complete the CI pipelines configuration. Anything I can help with?

**Comment by jeromelaban** [comment]
The pipeline is integrated, it's not started because it's from a fork, I'll fix that.

**Comment by ajpinedam** [comment]
> The pipeline is integrated, it's not started because it's from a fork, I'll fix that.

I had to use the fork since it seems I don't have access to this project.

**Pull request merged**
